import { useAppContext } from "@/components/appWrapper";
import Layout from "@/components/layout";
import { CheckIcon } from "@heroicons/react/24/solid";
import Head from "next/head";
import Link from "next/link";
import { MutableRefObject, useRef } from "react";
export default function Home() {
  const ref = useRef() as MutableRefObject<HTMLInputElement>;
  const { userInfo, session } = useAppContext();
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* TODO: Username selection */}
      <div className="grid">
        {!session ? (
          <button className="text-3xl font-bold text-center border m-auto px-2 py-1">
            <Link href={`/auth`}>Sign in First!</Link>
          </button>
        ) : userInfo.username === "" ? (
          <div className="mx-auto">
            <div>Select a username</div>
            <div className="flex">
              <input
                className="bg-neutral-900 border-neutral-100 border p-2"
                ref={ref}
              />
              <button
                className="border grid w-12 bg-neutral-100 text-neutral-900"
                onClick={async () => {
                  fetch(`/api/username?username=${ref.current.value}`);
                }}
              >
                <CheckIcon className="w-8 h-8 m-auto" />
              </button>
            </div>
          </div>
        ) : (
          <button className="text-3xl font-bold text-center border m-auto px-2 py-1">
            <Link href={`/@${userInfo.username}`}>Rate yourself!</Link>
          </button>
        )}
        {/* TODO: link share */}
        {/* <div>
        <div>Share your link:</div>
      </div> */}
      </div>
    </Layout>
  );
}
